XTAIN\Bundle\JoomlaBundle\Entity\Menu:
    type: entity
    table: menu
    repositoryClass: XTAIN\Bundle\JoomlaBundle\Entity\MenuRepository
    uniqueConstraints:
        idx_client_id_parent_id_alias_language:
            columns: [ client_id, parent_id, alias, language ]
    indexes:
        idx_componentid:
            columns: [ component_id, menutype, published, access ]
        idx_menutype:
            columns: [ menutype ]
        idx_left_right:
            columns: [ lft, rgt ]
        idx_alias:
            columns: [ alias ]
        idx_path:
            columns: [ path ]
        idx_language:
            columns: [ language ]
    id:
        id:
            type: integer
            length: 11
            generator:
                strategy: AUTO
    fields:
        menutype:
            type: string
            length: 24
        title:
            type: string
            length: 255
        alias:
            type: string
            length: 255
        note:
            type: string
            length: 255
        path:
            type: string
            length: 1024
        link:
            type: string
            length: 1024
        type:
            type: string
            length: 16
        published:
            type: smallint
            options:
                default: 0
        parentId:
            type: integer
            column: parent_id
            options:
                default: 1
                unsigned: true
        level:
            type: integer
            options:
                default: 0
                unsigned: true
        componentId:
            type: integer
            column: component_id
            options:
                default: 0
                unsigned: true
        checkedOut:
            type: integer
            column: checked_out
            options:
                default: 0
                unsigned: true
        checkedOutTime:
            type: datetime
            column: checked_out_time
            options:
                default: '0000-00-00 00:00:00'
        browserNav:
            type: smallint
            options:
                default: 0
        access:
            type: integer
            options:
                default: 0
                unsigned: true
        img:
            type: string
            length: 255
        templateStyleId:
            type: integer
            column: template_style_id
            options:
                default: 0
                unsigned: true
        params:
            type: json_array
        lft:
            type: integer
            options:
                default: 0
        rgt:
            type: integer
            options:
                default: 0
        home:
            type: smallint
            options:
                default: 0
                unsigned: true
        language:
            type: string
            length: 7
        clientId:
            type: smallint
            column: client_id
            type: smallint
            options:
                default: 0
    lifecycleCallbacks: {  }